/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Cloud.gltf --transform
Author: Kyyy_24 (https://sketchfab.com/luckyardrianto27)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cloud-lightning-d0e6edbfaedd40559a77611ade3c147b
Title: cloud lightning
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function Cloud(props: any) {
  // @ts-ignore
  const { nodes, materials } = useGLTF("/Cloud-transformed.glb")as unknown as {
    nodes: any;
    materials: any;
  };
  return (
    <group {...props} dispose={null}>
      <group position={[-0.7, 0.4, 0]} scale={0.0022}>
        <mesh
          geometry={nodes.th_bolt001_lighiting_0.geometry}
          material={materials.lighiting}
          position={[34.51, -75.24, 59.71]}
          rotation={[3.01, -0.14, 2.94]}
          scale={1.27}
        />
        <mesh
          geometry={nodes.th_bolt000_lighiting_0.geometry}
          material={materials.lighiting}
          position={[689.95, 36.55, 59.65]}
          rotation={[3.02, -0.15, 2.97]}
          scale={[-0.99, 0.99, 0.99]}
        />
        <mesh
          geometry={nodes.th_bolt002_lighiting_0.geometry}
          material={materials.lighiting}
          position={[508.19, -7.89, -28.24]}
          rotation={[0.16, 0.83, -0.65]}
          scale={[0.87, 1.14, 0.8]}
        />
        <mesh
          geometry={nodes.Mball034_Cloud_0.geometry}
          material={materials.Cloud}
          position={[37.28, 57.44, 21.33]}
          scale={0.93}
        />
        <mesh
          geometry={nodes.Sphere004_Rain_0.geometry}
          material={materials.Rain}
          position={[395.47, -636.17, -390.33]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere013_Rain_0.geometry}
          material={materials.Rain}
          position={[403.21, -518.13, -357.08]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere015_Rain_0.geometry}
          material={materials.Rain}
          position={[67.86, -442.67, -234.76]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere017_Rain_0.geometry}
          material={materials.Rain}
          position={[282.28, -287.55, 84.2]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere024_Rain_0.geometry}
          material={materials.Rain}
          position={[393.42, -162.93, 56.26]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere025_Rain_0.geometry}
          material={materials.Rain}
          position={[177.56, -313.94, 201.47]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere026_Rain_0.geometry}
          material={materials.Rain}
          position={[650.76, -561.96, 394.52]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere027_Rain_0.geometry}
          material={materials.Rain}
          position={[230.84, -319.34, -246.29]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere028_Rain_0.geometry}
          material={materials.Rain}
          position={[698.74, -192.71, 62.97]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere030_Rain_0.geometry}
          material={materials.Rain}
          position={[531.87, -559.72, 382.12]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere031_Rain_0.geometry}
          material={materials.Rain}
          position={[503.15, -340.96, -337.38]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere034_Rain_0.geometry}
          material={materials.Rain}
          position={[177.25, -136.81, -27.18]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere037_Rain_0.geometry}
          material={materials.Rain}
          position={[272.79, -257.52, -297.72]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere038_Rain_0.geometry}
          material={materials.Rain}
          position={[326.82, -245.15, -290.72]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere039_Rain_0.geometry}
          material={materials.Rain}
          position={[425.7, -170.02, -255.04]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere042_Rain_0.geometry}
          material={materials.Rain}
          position={[-10.95, -336.52, 232.74]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere043_Rain_0.geometry}
          material={materials.Rain}
          position={[-80.06, -340.76, -175.36]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere044_Rain_0.geometry}
          material={materials.Rain}
          position={[727.35, -531.98, 324.28]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere045_Rain_0.geometry}
          material={materials.Rain}
          position={[391.14, -274.49, 356.17]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere046_Rain_0.geometry}
          material={materials.Rain}
          position={[592.19, -628.48, -193.34]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere048_Rain_0.geometry}
          material={materials.Rain}
          position={[598.22, -639.35, -91.17]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere049_Rain_0.geometry}
          material={materials.Rain}
          position={[628.26, -263.69, -312.94]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere050_Rain_0.geometry}
          material={materials.Rain}
          position={[-2.07, -226.64, -236.89]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere051_Rain_0.geometry}
          material={materials.Rain}
          position={[2.99, -164.89, -115.89]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere052_Rain_0.geometry}
          material={materials.Rain}
          position={[343.75, -599.13, 121.86]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere053_Rain_0.geometry}
          material={materials.Rain}
          position={[935.82, -339.85, 240.94]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere054_Rain_0.geometry}
          material={materials.Rain}
          position={[928.92, -235.8, -199.16]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere055_Rain_0.geometry}
          material={materials.Rain}
          position={[305.62, -573.24, 113.52]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere056_Rain_0.geometry}
          material={materials.Rain}
          position={[209.78, -86.78, -220.51]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere057_Rain_0.geometry}
          material={materials.Rain}
          position={[387.51, -135.65, -294.05]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere058_Rain_0.geometry}
          material={materials.Rain}
          position={[350.32, -98.2, 212.03]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere059_Rain_0.geometry}
          material={materials.Rain}
          position={[-21.82, -522.43, 118.9]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere060_Rain_0.geometry}
          material={materials.Rain}
          position={[22.98, -451.64, -246.58]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere061_Rain_0.geometry}
          material={materials.Rain}
          position={[584.59, -20.67, 176.92]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere063_Rain_0.geometry}
          material={materials.Rain}
          position={[154.13, -131.67, -289.81]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere064_Rain_0.geometry}
          material={materials.Rain}
          position={[523.82, -72.37, 219.58]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere065_Rain_0.geometry}
          material={materials.Rain}
          position={[775.02, -128.05, -247.9]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere066_Rain_0.geometry}
          material={materials.Rain}
          position={[534.27, -489.64, -104.08]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere067_Rain_0.geometry}
          material={materials.Rain}
          position={[571.9, -152.74, 338.4]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere068_Rain_0.geometry}
          material={materials.Rain}
          position={[725.83, -210.61, 330.42]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere069_Rain_0.geometry}
          material={materials.Rain}
          position={[761.71, -437.39, -20.9]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere070_Rain_0.geometry}
          material={materials.Rain}
          position={[298.25, -6.67, -203.52]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere071_Rain_0.geometry}
          material={materials.Rain}
          position={[241.19, -454.44, -173.56]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere072_Rain_0.geometry}
          material={materials.Rain}
          position={[595.31, -428.86, -188.75]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere073_Rain_0.geometry}
          material={materials.Rain}
          position={[683.12, -91.62, -282.08]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere074_Rain_0.geometry}
          material={materials.Rain}
          position={[170.19, -180.84, -346.04]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere075_Rain_0.geometry}
          material={materials.Rain}
          position={[521.15, -409.01, 198.08]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere076_Rain_0.geometry}
          material={materials.Rain}
          position={[-33.19, -369.38, -112.56]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere082_Rain_0.geometry}
          material={materials.Rain}
          position={[333.57, -350.6, 242.19]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere083_Rain_0.geometry}
          material={materials.Rain}
          position={[-68.15, -178.6, -164.05]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere084_Rain_0.geometry}
          material={materials.Rain}
          position={[-50.99, -32.06, 149]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere087_Rain_0.geometry}
          material={materials.Rain}
          position={[-52.22, -315.91, 116.09]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere088_Rain_0.geometry}
          material={materials.Rain}
          position={[596.59, -351.51, 94.3]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere091_Rain_0.geometry}
          material={materials.Rain}
          position={[371.3, -330.35, -166.73]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere094_Rain_0.geometry}
          material={materials.Rain}
          position={[611.95, -318.32, -110.52]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere095_Rain_0.geometry}
          material={materials.Rain}
          position={[911.2, -3.87, -166.04]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere099_Rain_0.geometry}
          material={materials.Rain}
          position={[11.33, -57.78, 218.38]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere100_Rain_0.geometry}
          material={materials.Rain}
          position={[170.04, -65.17, 327.69]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere103_Rain_0.geometry}
          material={materials.Rain}
          position={[820.35, -126.54, -254.27]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere104_Rain_0.geometry}
          material={materials.Rain}
          position={[193.27, -246.67, -25.47]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere107_Rain_0.geometry}
          material={materials.Rain}
          position={[287.46, -161.44, 271.48]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere108_Rain_0.geometry}
          material={materials.Rain}
          position={[597.91, -239.86, -133.49]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere109_Rain_0.geometry}
          material={materials.Rain}
          position={[22.93, -96.69, 213.32]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere110_Rain_0.geometry}
          material={materials.Rain}
          position={[201.79, -62.78, -333.1]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere111_Rain_0.geometry}
          material={materials.Rain}
          position={[873.12, -89.5, 233.99]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere114_Rain_0.geometry}
          material={materials.Rain}
          position={[557.54, -163.86, 261.36]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere116_Rain_0.geometry}
          material={materials.Rain}
          position={[738.44, -115.96, -240.06]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere119_Rain_0.geometry}
          material={materials.Rain}
          position={[354.36, -167.22, -261.62]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere121_Rain_0.geometry}
          material={materials.Rain}
          position={[498.93, -181.66, -4.25]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere124_Rain_0.geometry}
          material={materials.Rain}
          position={[8.13, 1.87, -233.59]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere125_Rain_0.geometry}
          material={materials.Rain}
          position={[564.75, -95.98, -281.43]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere127_Rain_0.geometry}
          material={materials.Rain}
          position={[529.85, -40.71, 296.46]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere128_Rain_0.geometry}
          material={materials.Rain}
          position={[194.06, -97.5, -263.82]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere131_Rain_0.geometry}
          material={materials.Rain}
          position={[642.24, -160.47, -74.14]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere135_Rain_0.geometry}
          material={materials.Rain}
          position={[478.67, -133.16, -27.46]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere138_Rain_0.geometry}
          material={materials.Rain}
          position={[30.22, -123.13, 93.36]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere143_Rain_0.geometry}
          material={materials.Rain}
          position={[187.04, -126.32, 68.83]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere148_Rain_0.geometry}
          material={materials.Rain}
          position={[261.79, -109.52, -119.36]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere150_Rain_0.geometry}
          material={materials.Rain}
          position={[702.48, -57.22, -203.63]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere151_Rain_0.geometry}
          material={materials.Rain}
          position={[45.02, -108.64, 10.19]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere155_Rain_0.geometry}
          material={materials.Rain}
          position={[237.21, -93.24, -1.1]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere157_Rain_0.geometry}
          material={materials.Rain}
          position={[355.02, -32.74, 259.42]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
        <mesh
          geometry={nodes.Sphere158_Rain_0.geometry}
          material={materials.Rain}
          position={[816.85, -52.09, -56.17]}
          rotation={[0, 0, -0.49]}
          scale={[0.04, 0.11, 0.03]}
        />
        <mesh
          geometry={nodes.Sphere159_Rain_0.geometry}
          material={materials.Rain}
          position={[605.11, -76.97, 202.03]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere160_Rain_0.geometry}
          material={materials.Rain}
          position={[805.21, -47.37, -139.97]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere164_Rain_0.geometry}
          material={materials.Rain}
          position={[221.07, -70.16, -17.04]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere168_Rain_0.geometry}
          material={materials.Rain}
          position={[731.68, 5.51, 233.07]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere005_Rain_0.geometry}
          material={materials.Rain}
          position={[700.32, -376.01, 324.28]}
          rotation={[0, 0, -0.49]}
          scale={[0.11, 0.17, 0.07]}
        />
        <mesh
          geometry={nodes.Sphere006_Rain_0.geometry}
          material={materials.Rain}
          position={[355.09, -432.16, 324.28]}
          rotation={[0, 0, -0.49]}
          scale={[0.1, 0.15, 0.06]}
        />
        <mesh
          geometry={nodes.Sphere007_Rain_0.geometry}
          material={materials.Rain}
          position={[126.3, -526.31, 113.52]}
          rotation={[0, 0, -0.49]}
          scale={[0.08, 0.13, 0.05]}
        />
        <mesh
          geometry={nodes.Sphere008_Rain_0.geometry}
          material={materials.Rain}
          position={[226.3, -556.64, -357.08]}
          rotation={[0, 0, -0.49]}
          scale={[0.06, 0.17, 0.04]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Cloud-transformed.glb");

export default Cloud;
