/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Coffee.gltf --transform
Author: Rosnandie Yikie (https://sketchfab.com/rosnandie.yikie)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-963a9e5d288c42509886c5efd4fedd3c
Title: Coffee
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function Coffee(props: any) {
  // @ts-ignore
  const { nodes, materials } = useGLTF("/Coffee-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[2.85, 0, -0.51]} rotation={[-Math.PI / 2, 0, 0.57]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes["Sphere001_Material_#28_0"].geometry}
            material={materials.Material_28}
            position={[0.34, 38.27, -6.54]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes["Line001_Material_#29_0"].geometry}
            material={materials.Material_28}
            position={[0, 21.82, 33.97]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes["Cylinder001_Material_#30_0"].geometry}
            material={materials.Material_28}
            position={[0.55, 0, -7.66]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes["Object001_Material_#26_0"].geometry}
            material={materials.Material_26}
            position={[0.34, 38.27, -6.54]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Coffee-transformed.glb");

export default Coffee;
