/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 computer.gltf --transform
Author: Diego G. (https://sketchfab.com/empty_mirror)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voxel-web-development-50ad959d6c6b4799806c45bfa46ca550
Title: Voxel Web Development
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function NotebookLayout(props: any) {
  // @ts-ignore
  const { nodes, materials } = useGLTF("/computer-transformed.glb")as unknown as {
    nodes: any;
    materials: any;
  };
  return (
    <group {...props} dispose={null}>
        <group position={[0, -0.34, 0.37]} scale={0.4}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.palette}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["palette.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["palette.002"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      </group>
    </group>
  );
}

useGLTF.preload("/computer-transformed.glb");

export default NotebookLayout;
