/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 picture.gltf --transform
Author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/the-great-wave-off-kanagawa-katsushika-hokusai-f64171ed4ee243819a12a8031e9754d1
Title: The Great Wave off Kanagawa, Katsushika Hokusai
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function PictureWave(props: any) {
  // @ts-ignore
  const { nodes, materials } = useGLTF("/picture-transformed.glb")as unknown as {
    nodes: any;
    materials: any;
  };
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.34, 0.37]} scale={0.1}>
        <group position={[-10.01, -6.74, -0.99]}>
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited}
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_14.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_16.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_17.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_18.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_19.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_20.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_21.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_23.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_24.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_25.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_26.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_27.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_28.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_29.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_30.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_31.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_32.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_33.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_34.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_35.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_36.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_37.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_38.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_39.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_40.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_41.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_42.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_43.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_44.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_45.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_46.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_47.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
          <mesh
            geometry={nodes.Object_48.geometry}
            material={materials.Tsunami_by_hokusai_19th_century_edited_BW}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/picture-transformed.glb");

export default PictureWave;
